/*
 * Copyright (c) 2019 Lohmann & Birkner.
 * NOTICE:  All information contained herein is, and remains
 * the property of Lohmann & Birkner and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Lohmann & Birkner
 * and its suppliers and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Lohmann & Birkner.
 * http://www.lohmann-birkner.de/de/index.php
 *
 * Contributors:
 *    2019  gerschmann - initial API and implementation and/or initial documentation
 */
package de.lb.cpx.server.rule.services;

import de.lb.cpx.server.commons.dao.AbstractEntity;
import java.util.logging.Level;

/**
 * Exception will be generated by processing of different commandos from
 * RuleEditor
 *
 * @author gerschmann
 */
public class RuleEditorProcessException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    private final AbstractEntity errorEntity; // on processing of this entity was an error detected
    private final Level errorLevel;

    private RuleEditorProcessException(final AbstractEntity pEntity, final Level pLevel, final String pMessage) {
        super(pMessage);

        errorEntity = pEntity;
        errorLevel = pLevel;
    }

    public static RuleEditorProcessException createRuleEditorProcessException(final AbstractEntity pEntity, final Level pLevel, final String pMessage) {
        return new RuleEditorProcessException(pEntity, pLevel, pMessage);
    }

    public AbstractEntity getErrorEntity() {
        return errorEntity;
    }

    public Level getErrorLevel() {
        return errorLevel;
    }

}
